on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Fail
        run: exit 1

  test_failure:
    runs-on: ubuntu-latest
    needs: run
    if: failure()
    steps:
      - name: Send Joke
        run: |
          URL="https://official-joke-api.appspot.com/random_joke"
          RESPONSE=$(curl -s $URL)
          SETUP=$(echo $RESPONSE | jq -r '.setup')
          PUNCHLINE=$(echo $RESPONSE | jq -r '.punchline')
          BRANCH_NAME=${GITHUB_REF##*/}

          MESSAGE="Here's a joke for you:\n**$SETUP**\n*$PUNCHLINE*"

          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"$MESSAGE\"}" \
          ${{ secrets.DISCORD_LOG }}
